### ISSUE TITLE
404 error on docs hosted on your website

### ISSUE THREAD

**Issue by matu3ba** [mov-rax/zig-validate#1]
For example, https://mov-rax.github.io/zig-validate/#root;validate.ValidateWith.Target does not exist or is wrongly linked.
Is this an upstream issue with autodoc?

Reproduce with:
Open https://mov-rax.github.io/zig-validate/#root;validate.ValidateWith and click on [Target](https://mov-rax.github.io/zig-validate/#root;validate.ValidateWith.Target) in section "Values" at bottom

**Comment by matu3ba** [comment]
Reproduce with:
Open https://mov-rax.github.io/zig-validate/#root;validate.ValidateWith and click on [Target](https://mov-rax.github.io/zig-validate/#root;validate.ValidateWith.Target) in section "Values" at bottom

**Comment by mov-rax** [comment]
@matu3ba This seems to be an issue with autodoc. I've rebuilt the documentation and it doesn't seem to change the 404 Error when clicking on Target. Its a bit odd that it documents `Target` and `Validator` as `anyopaque` in the `Values` section of the page when they are defined as `type`.

**Comment by mov-rax** [comment]
Sorry for letting this issue linger for so long. I've updated the docs with the latest version of autodoc and this issue seems to no longer exist.
