### ISSUE TITLE
compile failed without any infomation

### ISSUE THREAD

**Issue by deathcodebind** [mov-rax/zig-validate#5]
I write the code bellow, which got "error: The following command exited with error code 5" before running the test

```
//utils.Comparable:
pub fn Comparable(comptime RHS: type) type {
    return struct {
        cmp: *const fn(*const @This(), *const RHS) CompareResult
    };
}
//utils.CompareResult
pub const CompareResult = enum(u8) {
    Greater = 0,
    Equal = 1,
    Less = 2,
};
pub fn Range(comptime T: type) type {
    const input_type_info = @typeInfo(T);
    switch (input_type_info) {
        .Int, .Float, .Bool => {},
        else => {
            @compileError("Range among non-numeric types is not supported");
        },
    }
    return struct {
        start: T = 0,
        end: T,
        step: T = 1,
        comparableSelf: utils.Comparable(Self) = validate.dynamic(utils.Comparable(Self), ComparableSelfImpl),
        comparableInnerType: utils.Comparable(T) = validate.dynamic(utils.Comparable(T), ComparableInnerTypeImpl),
        const Self = @This();
        const ComparableSelfImpl = struct {
            pub fn cmp(comparable: *const utils.Comparable(Self), rhs: *const Self) utils.CompareResult {
                const self = @fieldParentPtr(Self, "comparableSelf", comparable);
                if (((self.end - self.start) / self.step) - ((rhs.end - rhs.start) / rhs.step) > 0) {
                    return .Greater;
                }
                if (((self.end - self.start) / self.step) - ((rhs.end - rhs.start) / rhs.step) < 0) {
                    return .Less;
                }
                return .Equal;
            }
        };
        const ComparableInnerTypeImpl = struct {
            pub fn cmp(comparable: *const utils.Comparable(T), rhs: *const T) utils.CompareResult {
                const self = @fieldParentPtr(Self, "comparableInnerType", comparable);
                if (self.start > rhs) return .Greater;
                if (self.end < rhs) return .Less;
                return .Equal;
            }
        };
    };
}
test "Comparable" {
    var range_1 = Range(u32){ .end = 5 };
    var range_2 = Range(u32){ .end = 4 };
    try std.testing.expectEqual(range_1.comparableSelf.cmp(&range_1, &range_2), .Greater);
    try std.testing.expectEqual(range_1.comparableInnerType.cmp(&range_1, 3), .Equal);
}
```

**Comment by deathcodebind** [comment]
this problem actually would not happen when I use StaticDispatch, so I think it may have somewhere that reached the undefined behavior of zig

**Comment by mov-rax** [comment]
@deathcodebind what is the output of `zig version` on your install? I get an `error: The following command exited with error code 11` on version `0.11.0-dev.1836+28364166e`.

I am 99% certain this this is a bug within zig. If there was an error in zig-validate there should've been a descriptive compiler message stating what was wrong. I'll try and figure out what exactly causes it to error.

**Comment by pathologyenigma** [comment]
I use 0.11.0-dev.1898+36d47dd19 version of zig

**Comment by deathcodebind** [comment]
> @deathcodebind what is the output of `zig version` on your install? I get an `error: The following command exited with error code 11` on version `0.11.0-dev.1836+28364166e`.
> 
> I am 99% certain this this is a bug within zig. If there was an error in zig-validate there should've been a descriptive compiler message stating what was wrong. I'll try and figure out what exactly causes it to error.

zig version
0.11.0-dev.1898+36d47dd19

**Comment by mov-rax** [comment]
After some trial and error, it seems that the build fails because the struct `Comprable(Range(u32)` depends on itself.

```
src/validateTests.zig:396:12: error: struct 'validateTests.Comparable(validateTests.Range(u32))' depends on itself
    return struct {
           ^~~~~~
src/validate.zig:98:40: note: called from here
        var extractedVT = utils.extract(VTable, .vtable);
                          ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
src/validateTests.zig:419:60: note: called from here
        comparableSelf: Comparable(Self) = validate.dynamic(Comparable(Self), CompareImpl),
```

I have reduced it to a test like this to replicate what could cause the compiler to crash:
```zig
test "Break" {
    const Oof = Range(u32);
    const d = validate.dynamic(Comparable(Oof.Self), Oof.CompareImpl);
    _ = d;
}
```
I have made `Self` pub and simplified to a single implementation named `CompareImpl` that always returns `.Equal`.
commenting out `validate.dynamic` out makes the build work, so I took it outside of the struct and it returns the compile error I pasted above.

This seems to be a limitation of zig, not a bug in zig-validate.

**Comment by deathcodebind** [comment]
> After some trial and error, it seems that the build fails because the struct `Comprable(Range(u32)` depends on itself.
> 
> ```
> src/validateTests.zig:396:12: error: struct 'validateTests.Comparable(validateTests.Range(u32))' depends on itself
>     return struct {
>            ^~~~~~
> src/validate.zig:98:40: note: called from here
>         var extractedVT = utils.extract(VTable, .vtable);
>                           ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
> src/validateTests.zig:419:60: note: called from here
>         comparableSelf: Comparable(Self) = validate.dynamic(Comparable(Self), CompareImpl),
> ```
> 
> I have reduced it to a test like this to replicate what could cause the compiler to crash:
> 
> ```zig
> test "Break" {
>     const Oof = Range(u32);
>     const d = validate.dynamic(Comparable(Oof.Self), Oof.CompareImpl);
>     _ = d;
> }
> ```
> 
> I have made `Self` pub and simplified to a single implementation named `CompareImpl` that always returns `.Equal`. commenting out `validate.dynamic` out makes the build work, so I took it outside of the struct and it returns the compile error I pasted above.
> 
> This seems to be a limitation of zig, not a bug in zig-validate.

I see, since it is not a bug in zig-validate, maybe I needed to close this issue. thanks for your patient
